name: core
description: "@onytsukabatu"
publish_to: 'none'
version: 0.0.2+2

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  flutter_secure_storage: ^9.2.4
  get: ^4.7.2
  get_storage: ^2.1.1
  google_fonts: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0